[torch_generator] sort the special token by length
facebookresearch/ParlAI pull request #3315
Opened 2020-12-18 05:06 UTC by wyshi

sort the special token list by length, because in https://github.com/facebookresearch/ParlAI/blob/master/parlai/utils/bpe.py#L159-L167, 
`split = text.split(special_token)`.

e.g. if text = "ABCDEF", and special_token=['A', 'AB'], if they are not sorted, then text would become ['A', 'BCDEF'], instead of ['AB', 'CDEF'].

2020-12-18 14:53 UTC, stephenroller requested changes
I'm not fond of this. The user has total control over the ordering of the special tokens as of right now, and you're removing that. Just input a sorted list for the effect you want.

2020-12-18 18:38 UTC, wyshi commented
> I'm not fond of this. The user has total control over the ordering of the special tokens as of right now, and you're removing that. Just input a sorted list for the effect you want.

ok I agree. Then maybe we should add an explanation somewhere on how the special tokens are used? It took me a while and many pdbs to realize what's happening and why some special tokens are not split and some special tokens are...

2020-12-18 18:46 UTC, stephenroller commented
Sounds good

2021-01-06 03:18 UTC, stephenroller commented
Replaced with #3349.

2021-01-06 03:18 UTC, closed without merging